FootballManager.Web/Controllers/TournamentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using FootballManager.Domain;
using FootballManager.Service;
using FootballManager.Web.Common;
using FootballManager.Web.Models;
using FootballManager.Service.Interfaces;
using FootballManager.Web.Extensions;

namespace FootballManager.Web.Controllers
{
    public class TournamentController : BaseController
    {
        private readonly ITournamentService _tournamentService;
        private readonly ICountryService _countryService;

        public TournamentController(ITournamentService tournamentService, ICountryService countryService, IMapper mapper): base(mapper)
        {
            this._tournamentService = tournamentService;
            this._countryService = countryService;
        }

        // GET: Tournament
        public ActionResult Index()
        {
            var tournamentModels = GetTournamentList();
            if (Request.IsAjaxRequest())
            {
                return PartialView("_TournamentList", tournamentModels);
            }

            return View(tournamentModels);
        }

        public ActionResult Create()
        {
            ViewBag.CountryList = new SelectList(_countryService.GetList(), "CountryId", "CountryName");
            return PartialView("_Create");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TournamentViewModel model)
        {
            if (ModelState.IsValid)
            {
                var tournament = _mapper.Map<TournamentViewModel, Tournament>(model);
                _tournamentService.Insert(tournament);

                return PartialView("_TournamentList", GetTournamentList());
            }

            return Json(new JsonInfo(JsonStatus.Failed), JsonRequestBehavior.AllowGet);
        }

        public ActionResult Update(XeditableOptions editOptions)
        {
            if (editOptions == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound, "Bad Request");
            }
            int status = _tournamentService.UpdateInfo(editOptions.Pk, editOptions.Name, editOptions.Value);
            return Json(new JsonInfo(status), JsonRequestBehavior.AllowGet);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound, "Bad Request");
            }
            _tournamentService.DeleteById(id.Value);

            if (Request.IsAjaxRequest())
            {
                return PartialView("_TournamentList", GetTournamentList());
            }
            return Json(new JsonInfo(JsonStatus.Success), JsonRequestBehavior.AllowGet);
        }

        private IEnumerable<TournamentViewModel> GetTournamentList()
        {
            var tournaments = _tournamentService.GetList(x => true);
            var tournamentModels = _mapper.Map<IEnumerable<Tournament>, IEnumerable<TournamentViewModel>>(tournaments);
            return tournamentModels;
        } 
    }
}

FootballManager.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Football Manager", "Index", "Tournament", new {area = ""}, new {@class = "navbar-brand"})
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Tournament", "Index", "Tournament")</li>
                    <li>@Html.ActionLink("Team", "Index", "Team")</li>
                    <li>@Html.ActionLink("Player", "Index", "Player")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr/>
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Html.Partial("_Modal")"

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/lib")
    @Scripts.Render("~/bundles/app")

    @RenderSection("scripts", required: false)
</body>
</html>

FootballManager.Web/Views/Shared/_Modal.cshtml
<div id="standardModal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content" id="ModalContent">
            
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->